### ISSUE TITLE
Disable Agent worker when in test mode or via ENV var

### ISSUE THREAD

**Issue by blasterpal** [randy-girard/app_perf_rpm#1]
## Issue

When running Agent for various non-production use cases like where the AppPerf server isn't available or running specs, the agent should be shouldn't start and try to send data. When worker can't connect the following errors occur:

```
#<Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 5000>
E, [2017-04-05T19:38:41.968976 #48940] ERROR -- :
["/home/ubuntu/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/net/http.rb:879:in
```
## Question/Suggestion: 

Add Configuration option or ENV var to disable agent. `APP_PERF_DISABLE` for example. I'll look into making a PR for above, unless you disagree with approach.

**Comment by randy-girard** [comment]
I think a config option in the agent would be good, and then it can be set in the application to the evaluation of the environment == 'test' or not

**Comment by randy-girard** [comment]
It could also support the env variable as well.
