### ISSUE TITLE
Use more faster way to measure time

### ISSUE THREAD

**Issue by stereobooster** [randy-girard/app_perf_rpm#10]
see https://samsaffron.com/archive/2017/10/18/fastest-way-to-profile-a-method-in-ruby

**Comment by randy-girard** [comment]
Thanks. I will look into using this method!

**Comment by randy-girard** [comment]
Being addressed here https://github.com/randy-girard/app_perf_rpm/pull/11/files#diff-f5a5932b5ac7b16d7eda7f77d75246ecR153
