### ISSUE TITLE
undefined method `path_parameters' for nil:NilClass

### ISSUE THREAD

**Issue by peter-umb** [randy-girard/app_perf_rpm#14]
Rails 4.2.8 - Ruby 2.2.6 - Passenger 5.1

All of the partials included through 'render' throw this error in production:
undefined method `path_parameters' for nil:NilClass

The stack traces do not offer much insight. They only list from the controller to the view file and end on render lines like this:

`  = render partial: 'data_mapper'
`

I believe the error comes from lines 10 and 11 in this file:
https://github.com/randy-girard/app_perf_rpm/blob/704f3c9d618c6370feef9ec232e60dbe5c96919d/lib/app_perf_rpm/instruments/action_view.rb

The app-perf host is working quite well. It seems to update much faster than NewRelic. Not quite sure why I am experiencing this error.

**Comment by randy-girard** [comment]
Try updating the gem. I encountered that issue earlier today and fixed it.
