### ISSUE TITLE
Monitor rake taskas

### ISSUE THREAD

**Issue by lcguida** [randy-girard/app_perf_rpm#18]
First of all, nice work with this project. 

I've been experimenting with it and so far it looks good.

I would like to know/suggest if there's any plan on monitoring rake tasks (or background jobs). This would be very useful for the non standard Rails app. 

I would be willing to help if you have any plans to work with this.

**Comment by randy-girard** [comment]
It currently should be instrumenting sidekiq jobs. Resque/Delayed job/Other aren't in there, but could be added. There currently isn't a separation in the web app to easily break this down yet, but its something I want to add.

Regarding rake tasks, if they are using any code that is instrumented, it should show up, however it will be sampled. I'm not sure what you are looking for exactly there or what you are using.

**Comment by randy-girard** [comment]
Going to start adding to project to monitor rake tasks.
