### ISSUE TITLE
Use route instead of URL

### ISSUE THREAD

**Issue by stereobooster** [randy-girard/app_perf_rpm#7]
Rails can provide route in form of `Controller#Action` and Sinatra in form of `GET /some/path/:id`

**Comment by randy-girard** [comment]
Can you please provide some more detail for this?

**Comment by stereobooster** [comment]
The idea is simple. Instead of logging `/some/resource/1`, `/some/resource/2`, `/some/resource/3` we can log `/some/resource/:id`. This correlates with what [opentracing suggests](https://github.com/opentracing/specification/blob/master/specification.md#start-a-new-span)

You can look into Skylight code on how to do this:
- [sinatra](https://github.com/skylightio/skylight-ruby/blob/73404bf150fe1597f923a5e937944d5a185b8258/lib/skylight/probes/sinatra.rb#L27)
- [rails](https://github.com/skylightio/skylight-ruby/blob/73404bf150fe1597f923a5e937944d5a185b8258/lib/skylight/probes/action_controller.rb#L31)

**Comment by randy-girard** [comment]
OK, yes that makes sense. Thanks!
