### ISSUE TITLE
Switch to opentracing protocol?

### ISSUE THREAD

**Issue by stereobooster** [randy-girard/app_perf_rpm#8]
It is close enough in semantics. See [specification.md](https://github.com/opentracing/specification/blob/master/specification.md)

**Comment by randy-girard** [comment]
I will look into migrating to this after I finish up some things. I think this will help a lot with getting other language APM built as well. Thanks!

**Comment by stereobooster** [comment]
I found only one ruby "alternative" with opentracing support: [ruby-sensor](https://github.com/instana/ruby-sensor), but it is not clear what is the license.

And [there are a lot of frontends for opentracing](http://opentracing.io/documentation/pages/supported-tracers). This [one looks nice](https://medium.com/opentracing/take-opentracing-for-a-hotrod-ride-f6e3141f7941).

What I missing is good client/instrumenter for ruby. I want instrumenter equivalent to Skylight (in sense of tools coverage and performance), some set of tools for [request_id](https://github.com/remind101/request_id) and reporting with opentracing protocol.

**Comment by MACscr** [comment]
This would be huge and as you mentioned, would make it much easier to support other languages, such as php. =)

**Comment by randy-girard** [comment]
Yup, I have to clean up some final things I have been working on and them I may look at switching over to this. Trying to find the time lately :(

**Comment by randy-girard** [comment]
I actually just started working on this over the past weekend :) Unfortunately my spare time is low right now, but I am working on it when I can.

**Comment by randy-girard** [comment]
@MACscr Just an update, I am getting closer to this. Got most of the data pushing up, just have to do some work handling the new data formats

**Comment by stereobooster** [comment]
If you do open tracing thing you should have some kind of "coercion id". Not sure how you solved this problem, but if you haven't dived into it yet I know gem which does it https://github.com/stereobooster/kiev. It is also do logging, but part about coercion id can be extracted.

**Comment by randy-girard** [comment]
If you are referring to ability to do distribited tracing, it will be in there. Sorry, havent had a chance to look at your repo yet.

**Comment by randy-girard** [comment]
Here is an example of a distributed trace. It started with a web request, which called sidekiq to process a job.

![image](https://user-images.githubusercontent.com/91918/32329836-99657cd6-bfb4-11e7-98ec-0e811437f7ca.png)

**Comment by stereobooster** [comment]
Oh, nice. Is there any documentation about your coercion id implementation? What about HTTP calls?

**Comment by randy-girard** [comment]
@stereobooster Here is an example, https://github.com/randy-girard/app_perf_rpm/pull/11/files#diff-bf6dfcd65793ca316eebc0eaccdfb914R62

**Comment by stereobooster** [comment]
I see you have all those instrumentations nice. Also would be useful to expose trace_id (also called coercion_id and request_id) to be used in logs. Maybe you already doing it. I haven't checked all source
